name: CI dothelook
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    name: Cloud Run Deployment Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependency
        working-directory: "packages/web-client-next"
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Setup and run build on app
        working-directory: "packages/web-client-next"
        run: |
          npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          #NEXT_BACKEND_URL: "https://webbot-image-sync-qvde2butpa-uc.a.run.app"
          NEXT_BACKEND_URL: "https://webbot-image-sync-314035436999.us-central1.run.app"
          NEXT_ACCESS_KEY: "e191921352124a06a09bb811a86a5c3a"
          # GA_TRACKING_ID: "G-HHK6NNEJNF"
          NEXT_STAGING_ENV: "false"
          NEXT_IS_KIOSK_ENABLED: "false"
          NEXT_SUPER_ADMIN_USER_NAME: "dothelook"
          # NEXT_INSTANCE_LOGO: "https://www.budgettravel.com/assets/bt_logo_bg.svg"
          NEXT_AURA_HEADER_THEME: "light"
          NEXT_SHARED_PROFILE_ON_ROOT: "dothelook"
          NEXT_CURRENT_STORE_NAME: "dothelook"
          NEXT_CURRENT_STORE_ID: "23063956"
          # NEXT_HOME_PAGE_URL: "https://www.budgettravel.com"
          NEXT_ENABLE_VIEW_SIMILAR_PRODUCTS: "false"
          NEXT_ENABLE_RECOMMENDATIONS: "false"
          NEXT_IS_STORE_INSTANCE: "true"
          NEXT_ADMIN_USER_ID: "173081113277330"
          NEXT_AURA_YFRET_USER_COLL_BASE_URL: "https://auraprod.unthink.ai"
          NEXT_ENABLE_VENLY: "false"
          NEXT_WEBBOT_NFT_SERVICE__BASE_URL: ""
          NEXT_PDP_PAGE_ENABLED: "false"
          NEXT_PAYMENT_URL: "https://unthink-dropp-payment-prod-314035436999.us-central1.run.app"

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.DEV_GCP_SA_KEY_NEW }}
          export_default_credentials: true
      - name: Authorize
        working-directory: "packages/web-client-next"
        run: |
          gcloud auth configure-docker us-docker.pkg.dev --quiet
      
      - name: Build
        working-directory: "packages/web-client-next"
        run: |
          docker build --tag us-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT_ID }}/gcr.io/unthink-ui-gatsby-dothelook-ui-v2 .
      
      - name: Push
        working-directory: "packages/web-client-next"
        run: |
          docker push us-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT_ID }}/gcr.io/unthink-ui-gatsby-dothelook-ui-v2
      
      - name: Deploy
        working-directory: "packages/web-client-next"
        run: |
          gcloud run deploy unthink-ui-gatsby-dothelook-ui-v2 \
          --region us-central1 \
          --image us-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT_ID }}/gcr.io/unthink-ui-gatsby-dothelook-ui-v2 \
          --platform managed \
          --project ${{ secrets.DEV_GCP_PROJECT_ID }}