name: CI dothelook
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    name: Cloud Run Deployment Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependency
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps
      - name: Setup and run build on app
        run: |
          npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          #GATSBY_BACKEND_URL: "https://webbot-image-sync-qvde2butpa-uc.a.run.app"
          GATSBY_BACKEND_URL: "https://webbot-image-sync-314035436999.us-central1.run.app"
          GATSBY_ACCESS_KEY: "e191921352124a06a09bb811a86a5c3a"
          GA_TRACKING_ID: "G-HHK6NNEJNF"
          GATSBY_STAGING_ENV: "false"
          GATSBY_IS_KIOSK_ENABLED: "false"
          GATSBY_SUPER_ADMIN_USER_NAME: "dothelook"
          # GATSBY_INSTANCE_LOGO: "https://www.budgettravel.com/assets/bt_logo_bg.svg"
          GATSBY_AURA_HEADER_THEME: "light"
          GATSBY_SHARED_PROFILE_ON_ROOT: "dothelook"
          GATSBY_CURRENT_STORE_NAME: "dothelook"
          GATSBY_CURRENT_STORE_ID: "23063956"
          # GATSBY_HOME_PAGE_URL: "https://www.budgettravel.com"
          GATSBY_ENABLE_VIEW_SIMILAR_PRODUCTS: "false"
          GATSBY_ENABLE_RECOMMENDATIONS: "false"
          GATSBY_IS_STORE_INSTANCE: "true"
          GATSBY_ADMIN_USER_ID: "173081113277330"
          GATSBY_AURA_YFRET_USER_COLL_BASE_URL: "https://auraprod.unthink.ai"
          GATSBY_ENABLE_VENLY: "false"
          GATSBY_WEBBOT_NFT_SERVICE__BASE_URL: ""
          GATSBY_PDP_PAGE_ENABLED: "false"
          GATSBY_PAYMENT_URL: "https://unthink-dropp-payment-prod-314035436999.us-central1.run.app"
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DEV_GCP_SA_KEY_NEW }}
      - name: Setup GCP CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
      - name: Deploy
        run: |
          gcloud run deploy unthink-ui-gatsby-dothelook-V2 \
          --region us-central1 \
          --source . \
          --platform managed